import { Category, Product, Order } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Seragam & Atribut Resmi',
    slug: 'seragam-atribut-resmi',
    description: 'Topi upacara, dasi, ikat pinggang, dan kaos kaki resmi SMKN 11 Bandung.',
    icon: 'Tag',
  },
  {
    id: 'cat-2',
    name: 'Pakaian & Seragam Sekolah',
    slug: 'pakaian-seragam-sekolah',
    description: 'Jas almamater (almet), baju batik identitas, dan setelan seragam olahraga SMKN 11 Bandung.',
    icon: 'Shirt',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Topi Upacara Bordir SMKN 11 Bandung',
    slug: 'topi-upacara-bordir-smkn-11-bandung',
    description: 'Topi upacara resmi hari Senin warna abu-abu kombinasi biru tua dengan bordir identitas SMKN 11 Bandung. Bagian belakang dilengkapi perekat velcro fleksibel.',
    price: 18000,
    stock: 95,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-2',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Sabuk / Ikat Pinggang Gesper Logam SMKN 11 Bandung',
    slug: 'sabuk-ikat-pinggang-gesper-logam-smkn-11-bandung',
    description: 'Ikat pinggang sekolah standar tata tertib SMKN 11 Bandung dengan kepala gesper kuningan timbul logo sekolah, tali nylon hitam tebal awet.',
    price: 20000,
    stock: 85,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-3',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Dasi Abu-Abu Resmi SMKN 11 Bandung (Bordir Logo)',
    slug: 'dasi-abu-abu-resmi-smkn-11-bandung',
    description: 'Dasi sekolah resmi warna abu-abu SMA/SMK dengan bordir komputer emblem logo SMKN 11 Bandung. Bahan twist halus, rapi, dan mudah disetrika.',
    price: 15000,
    stock: 120,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-4',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Kaos Kaki Putih Telapak Hitam Bordir SMKN 11',
    slug: 'kaos-kaki-putih-telapak-hitam-smkn-11',
    description: 'Kaos kaki panjang di atas mata kaki standar tata tertib sekolah, terdapat rajutan logo SMKN 11 Bandung di samping. Bahan katun PE tebal dan menyerap keringat.',
    price: 15000,
    stock: 100,
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pasang',
  },
  {
    id: 'prod-5',
    categoryId: 'cat-2',
    categoryName: 'Pakaian & Seragam Sekolah',
    name: 'Jas Almamater (Almet) Resmi SMKN 11 Bandung',
    slug: 'jas-almamater-almet-resmi-smkn-11-bandung',
    description: 'Jas almamater (almet) resmi SMKN 11 Bandung warna biru khas dengan bordir logo sekolah di dada kiri dan kancing timbul berlogo.',
    price: 135000,
    stock: 75,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-6',
    categoryId: 'cat-2',
    categoryName: 'Pakaian & Seragam Sekolah',
    name: 'Baju Batik Khas SMKN 11 Bandung',
    slug: 'baju-batik-khas-smkn-11-bandung',
    description: 'Kain batik motif resmi identitas SMKN 11 Bandung untuk seragam hari Kamis dan Jumat. Bahan katun sanforized adem dan nyaman.',
    price: 85000,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-7',
    categoryId: 'cat-2',
    categoryName: 'Pakaian & Seragam Sekolah',
    name: 'Setelan Seragam Olahraga SMKN 11 Bandung',
    slug: 'setelan-seragam-olahraga-smkn-11-bandung',
    description: 'Setelan kaos olahraga lengan pendek dan celana training resmi SMKN 11 Bandung. Bahan elastis, adem, dan menyerap keringat dengan baik.',
    price: 95000,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'set',
  },
];

export const INITIAL_ORDERS: Order[] = [];

