import { Category, Product, Order } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Seragam & Atribut Resmi',
    slug: 'seragam-atribut-resmi',
    description: 'Dasi, topi upacara, ikat pinggang bordir, badge OSIS, bet lokasi Kota Bandung, dan kaos kaki resmi SMKN 11 Bandung.',
    icon: 'Tag',
  },
  {
    id: 'cat-2',
    name: 'Pakaian Praktik & Seragam Jurusan',
    slug: 'pakaian-praktik-jurusan',
    description: 'Wearpack kerja praktik RPL/TKJ, rompi kejuruan, baju batik sekolah, dan seragam olahraga SMKN 11.',
    icon: 'Shirt',
  },
  {
    id: 'cat-3',
    name: 'Buku & Perlengkapan Belajar',
    slug: 'buku-perlengkapan-belajar',
    description: 'Buku jurnal PKL / Praktik Kerja Lapangan, buku folio bergaris, map raport ijazah, dan alat tulis ujian.',
    icon: 'BookOpen',
  },
  {
    id: 'cat-4',
    name: 'Merchandise & Kejuruan',
    slug: 'merchandise-kejuruan',
    description: 'Lanyard eksklusif SMKN 11 Bandung, ID card holder, mug jurusan RPL/DKV, pin enamel, dan stiker laptop coding.',
    icon: 'Sparkles',
  },
  {
    id: 'cat-5',
    name: 'Kantin Sehat Koperasi',
    slug: 'kantin-sehat-koperasi',
    description: 'Roti bakar panggang, minuman segar, susu UHT, snack higienis, dan air mineral untuk bekal siswa.',
    icon: 'Coffee',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Seragam & Atribut Resmi
  {
    id: 'prod-1',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Dasi Abu-Abu Resmi SMKN 11 Bandung (Bordir Logo)',
    slug: 'dasi-abu-abu-resmi-smkn-11-bandung',
    description: 'Dasi sekolah resmi warna abu-abu SMA/SMK dengan bordir komputer emblem logo SMKN 11 Bandung. Bahan twist halus, rapi, dan mudah disetrika.',
    price: 15000,
    stock: 120,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-2',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Topi Upacara Bordir SMKN 11 Bandung',
    slug: 'topi-upacara-bordir-smkn-11-bandung',
    description: 'Topi upacara resmi hari Senin warna abu-abu kombinasi biru tua dengan bordir identitas SMKN 11 Bandung. Bagian belakang dilengkapi perekat velcro fleksibel.',
    price: 18000,
    stock: 95,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-3',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Sabuk / Ikat Pinggang Gesper Logam SMKN 11 Bandung',
    slug: 'sabuk-ikat-pinggang-gesper-logam-smkn-11-bandung',
    description: 'Ikat pinggang sekolah standar tata tertib SMKN 11 Bandung dengan kepala gesper kuningan timbul logo sekolah, tali nylon hitam tebal awet.',
    price: 20000,
    stock: 85,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-4',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Paket Badge Bordir Lengkap (Bet Lokasi + OSIS + Bendera Merah Putih)',
    slug: 'paket-badge-bordir-lengkap-smkn-11',
    description: 'Set atribut jahit seragam: Bet lokasi Kota Bandung, Nama Sekolah SMKN 11 Bandung, Bet saku OSIS SMK, dan Bet Bendera Merah Putih bordir presisi.',
    price: 12000,
    stock: 150,
    image: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'set',
  },
  {
    id: 'prod-5',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Kaos Kaki Putih Telapak Hitam Bordir SMKN 11 (2 Pasang)',
    slug: 'kaos-kaki-putih-telapak-hitam-smkn-11',
    description: 'Kaos kaki panjang di atas mata kaki standar tata tertib sekolah, terdapat rajutan logo SMKN 11 Bandung di samping. Bahan katun PE tebal dan menyerap keringat.',
    price: 17500,
    stock: 100,
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pack',
  },
  {
    id: 'prod-6',
    categoryId: 'cat-1',
    categoryName: 'Seragam & Atribut Resmi',
    name: 'Kerudung / Jilbab Putih Segiempat Siswi SMKN 11',
    slug: 'kerudung-jilbab-putih-segiempat-siswi',
    description: 'Jilbab putih polos bahan katun paris/voal premium adem tidak menerawang, tegak di dahi dan nyaman dipakai seharian di sekolah.',
    price: 25000,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },

  // 2. Pakaian Praktik & Seragam Jurusan
  {
    id: 'prod-7',
    categoryId: 'cat-2',
    categoryName: 'Pakaian Praktik & Seragam Jurusan',
    name: 'Wearpack / Baju Praktik Jurusan RPL & IT SMKN 11 Bandung',
    slug: 'wearpack-baju-praktik-jurusan-rpl-smkn-11',
    description: 'Baju kerja bengkel/lab komputer lengan pendek warna biru dongker kombinasi abu, bahan American Drill tebal berkualitas dengan bordir jurusan RPL.',
    price: 125000,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-8',
    categoryId: 'cat-2',
    categoryName: 'Pakaian Praktik & Seragam Jurusan',
    name: 'Rompi Kejuruan Bordir Komputer SMKN 11',
    slug: 'rompi-kejuruan-bordir-komputer-smkn-11',
    description: 'Rompi resmi kejuruan bahan kain drill furing jala nyaman, saku fungsional untuk praktikum dan tugas lapangan.',
    price: 75000,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-9',
    categoryId: 'cat-2',
    categoryName: 'Pakaian Praktik & Seragam Jurusan',
    name: 'Baju Batik Khas SMKN 11 Bandung',
    slug: 'baju-batik-khas-smkn-11-bandung',
    description: 'Kain batik motif resmi identitas SMKN 11 Bandung untuk seragam hari Kamis dan Jumat. Bahan katun sanforized adem.',
    price: 85000,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },

  // 3. Buku & Perlengkapan Belajar
  {
    id: 'prod-10',
    categoryId: 'cat-3',
    categoryName: 'Buku & Perlengkapan Belajar',
    name: 'Buku Jurnal Laporan PKL / Prakerin SMKN 11 Bandung',
    slug: 'buku-jurnal-laporan-pkl-prakerin-smkn-11',
    description: 'Buku panduan dan catatan kegiatan harian Praktik Kerja Lapangan (PKL) resmi yang disahkan oleh Pokja Hubin SMKN 11 Bandung.',
    price: 25000,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'buku',
  },
  {
    id: 'prod-11',
    categoryId: 'cat-3',
    categoryName: 'Buku & Perlengkapan Belajar',
    name: 'Buku Tulis Hardcover Folio Bergaris 100 Lembar',
    slug: 'buku-tulis-hardcover-folio-bergaris-100-lembar',
    description: 'Buku catatan tebal folio bergaris isi 100 lembar untuk laporan praktikum, produktif kejuruan, dan modul pembelajaran.',
    price: 14000,
    stock: 90,
    image: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'buku',
  },
  {
    id: 'prod-12',
    categoryId: 'cat-3',
    categoryName: 'Buku & Perlengkapan Belajar',
    name: 'Map Ijazah & Sertifikat Kompetensi SMKN 11 (Embos Emas)',
    slug: 'map-ijazah-sertifikat-kompetensi-smkn-11',
    description: 'Map ijazah bahan ASE tebal motif kulit jeruk dengan hotprint foil emas logo resmi SMKN 11 Bandung dan plastik mika isi 10 pasang.',
    price: 35000,
    stock: 70,
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },

  // 4. Merchandise & Kejuruan
  {
    id: 'prod-13',
    categoryId: 'cat-4',
    categoryName: 'Merchandise & Kejuruan',
    name: 'Lanyard Cardholder Siswa SMKN 11 Bandung (Tali Biru Navy)',
    slug: 'lanyard-cardholder-siswa-smkn-11-bandung',
    description: 'Tali id card sublimasi 2 sisi motif khas SMKN 11 Bandung dilengkapi stopper, pengait besi krom tebal, dan case id card transparan.',
    price: 20000,
    stock: 110,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-14',
    categoryId: 'cat-4',
    categoryName: 'Merchandise & Kejuruan',
    name: 'Gantungan Kunci Akrilik Logo SMKN 11 Bandung',
    slug: 'gantungan-kunci-akrilik-logo-smkn-11',
    description: 'Gantungan kunci 2 sisi bahan akrilik bening tebal 3mm gambar logo SMKN 11 Bandung tajam dan tahan air.',
    price: 8000,
    stock: 150,
    image: 'https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pcs',
  },
  {
    id: 'prod-15',
    categoryId: 'cat-4',
    categoryName: 'Merchandise & Kejuruan',
    name: 'Pack Stiker Jurusan RPL & Coding (Isi 12 Stiker Vinyl)',
    slug: 'pack-stiker-jurusan-rpl-coding',
    description: 'Koleksi stiker die-cut vinyl anti air laminasi matte: Logo SMKN 11, Next.js, React, Tailwind, TypeScript, Git, VSCode, dan slogan Programmer 11.',
    price: 12000,
    stock: 100,
    image: 'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'pack',
  },

  // 5. Kantin Sehat Koperasi
  {
    id: 'prod-16',
    categoryId: 'cat-5',
    categoryName: 'Kantin Sehat Koperasi',
    name: 'Roti Bakar Bandung Coklat Keju Crunchy',
    slug: 'roti-bakar-bandung-coklat-keju-crunchy',
    description: 'Roti tawar lembut dipanggang wangi mentega dengan isian coklat meses melimpah dan taburan keju parut.',
    price: 8000,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'porsi',
  },
  {
    id: 'prod-17',
    categoryId: 'cat-5',
    categoryName: 'Kantin Sehat Koperasi',
    name: 'Susu Ultra Milk Rasa Coklat 250ml',
    slug: 'susu-ultra-milk-rasa-coklat-250ml',
    description: 'Susu cair steril UHT rasa coklat lezat untuk menambah energi belajar di kelas.',
    price: 6500,
    stock: 75,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    unit: 'kotak',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderCode: 'MKT-20260904-0001',
    studentName: 'Rian Maulana Hidayat',
    studentClass: 'XII RPL 1',
    whatsappNumber: '081223344556',
    deliveryMethod: 'pickup',
    deliveryFee: 0,
    paymentMethod: 'cash',
    paymentStatus: 'unpaid',
    notes: 'Saya ambil jam istirahat pertama di koperasi ya pak/bu.',
    totalPrice: 53000,
    status: 'pending',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        productName: 'Dasi Abu-Abu Resmi SMKN 11 Bandung (Bordir Logo)',
        price: 15000,
        quantity: 1,
        subtotal: 15000,
      },
      {
        id: 'item-2',
        productId: 'prod-2',
        productName: 'Topi Upacara Bordir SMKN 11 Bandung',
        price: 18000,
        quantity: 1,
        subtotal: 18000,
      },
      {
        id: 'item-3',
        productId: 'prod-3',
        productName: 'Sabuk / Ikat Pinggang Gesper Logam SMKN 11 Bandung',
        price: 20000,
        quantity: 1,
        subtotal: 20000,
      },
    ],
  },
  {
    id: 'ord-2',
    orderCode: 'MKT-20260904-0002',
    studentName: 'Nabila Putri Azzahra',
    studentClass: 'XI AKL 2',
    whatsappNumber: '085799887766',
    deliveryMethod: 'delivery',
    deliveryFee: 2000,
    deliveryAddress: 'Gedung B Lantai 2 - Ruang XI AKL 2 (Meja Depan Baris 2)',
    paymentMethod: 'transfer',
    paymentStatus: 'paid',
    paymentProofUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400',
    notes: 'Tolong diantar sebelum jam 10 ya ka, terima kasih.',
    totalPrice: 47000,
    status: 'processing',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    items: [
      {
        id: 'item-4',
        productId: 'prod-6',
        productName: 'Kerudung / Jilbab Putih Segiempat Siswi SMKN 11',
        price: 25000,
        quantity: 1,
        subtotal: 25000,
      },
      {
        id: 'item-5',
        productId: 'prod-13',
        productName: 'Lanyard Cardholder Siswa SMKN 11 Bandung (Tali Biru Navy)',
        price: 20000,
        quantity: 1,
        subtotal: 20000,
      },
    ],
  },
];
